<a href="https://colab.research.google.com/github/junsoo321/public-repository/blob/main/procession(~2-21).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
A=np.array([[1,2,3,4],[5,6,7,8]])
print(A[0])
print(A[0,:])
print(A[1])
print(A[1,:])
print(A[:,0])
print(A[:,1])
print(A[:,2])
print(A[:,3])

print('\n\n')

A=np.array([[1,2],[3,4]])
B=np.array([[4,1],[5,2]])

print(A+B)
print(np.add(A,B))
print(A-B)
print(np.subtract(A,B))

print('\n\n')

A=np.arange(9).reshape(3,3)
print(A)
c=10
print(np.multiply(c,A))
print(c*A)

print('\n\n')

A=np.array([[1,2,3],[4,5,6]])
B=np.array([[4,1],[5,2],[1,2]])
print(A)
print(B)
print(A.dot(B))
print(np.dot(A,B))

print('\n\n')

A=np.array([[1,2],[3,4]])
B=np.array([[4,1],[5,2]])
print(A*B)
print(np.multiply(A,B))

print('\n\n')

X=np.array([[1,2],[3,4],[5,6]])
print(X)
print(X.T)
print(np.transpose(X))

print('\n\n')

I=np.eye(3)
A=np.arange(9).reshape(3,3)
print(A)

print((np.dot(A,I)==A).all())
print((np.dot(I,A)==A).all())

print('\n\n')

A=np.array([[1,2],[3,4]])
invA=np.linalg.inv(A)
print(invA)

print(np.dot(A,invA))
print(np.round(np.dot(A,invA)))
print(np.round(np.dot(invA,A)))

[1 2 3 4]
[1 2 3 4]
[5 6 7 8]
[5 6 7 8]
[1 5]
[2 6]
[3 7]
[4 8]



[[5 3]
 [8 6]]
[[5 3]
 [8 6]]
[[-3  1]
 [-2  2]]
[[-3  1]
 [-2  2]]



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]
[[ 0 10 20]
 [30 40 50]
 [60 70 80]]



[[1 2 3]
 [4 5 6]]
[[4 1]
 [5 2]
 [1 2]]
[[17 11]
 [47 26]]
[[17 11]
 [47 26]]



[[ 4  2]
 [15  8]]
[[ 4  2]
 [15  8]]



[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]



[[0 1 2]
 [3 4 5]
 [6 7 8]]
True
True



[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
